name: Community Support Request
about: Request support from the community
title: "[Support]: "
labels: ["community-support"]
assignees:
  - ""

body:
  - type: markdown
    attributes:
      value: |
        <!-- Provide a clear and concise description of your support request. -->

  - type: input
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of your support request.
      required: true

  - type: input
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any additional information or context that may be helpful.

required:
  - description
