name: Feature Request
description: Submit a feature request
title: "[Feature Request]: "
labels: ["feature request", "enhancement"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request! Please provide us with the details below.
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more information?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature you would like to request in detail.
      placeholder: Please provide a clear and concise description.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Current Version
      description: What version of our software are you currently using?
      placeholder: v1.6.0
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Explain how this feature would benefit your use case or workflow.
      placeholder: Please provide examples or scenarios where this feature would be useful.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this feature request, you agree to follow our [Code of Conduct](https://github.com/yuchuehw/DigitsSolver/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
