name: Support Request
about: Request assistance or support for the project
title: "[Support]: "
labels: ["support"]
assignees:
  - octocat

body:
  - type: markdown
    attributes:
      value: |
        <!-- Provide a clear and concise description of the issue or problem you are experiencing. -->

  - type: input
    id: description
    attributes:
      label: Description
      description: Provide a clear and concise description of the issue or problem you are experiencing.
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: If applicable, provide a detailed step-by-step guide on how to reproduce the issue.

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen.

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: Describe what is currently happening or the error message/behavior you are encountering.

  - type: input
    id: project-version
    attributes:
      label: Project Version
      description: Specify the version or release number of the project.
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating System
      description: Mention the operating system and version you are using.

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Specify the Python version you are using.

  - type: input
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any other relevant information about your environment.

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the issue.

  - type: textarea
    id: logs
    attributes:
      label: Logs or Error Messages
      description: If applicable, include any relevant logs or error messages related to the issue.

  - type: textarea
    id: code
    attributes:
      label: Code Snippets
      description: If applicable, include any relevant code snippets that might help identify the problem.

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context or information about the issue that may be helpful.

required:
  - description
  - project-version
